const sidebars = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Documentation',
      items: [
        {
          type: 'autogenerated',
          dirName: 'docs',
        },
      ],
    },
    {
      type: 'category',
      label: 'Features',
      items: [
        {
          type: 'autogenerated',
          dirName: 'features',
        },
      ],
    },
  ],
};

export default sidebars;